version: '3'
services: 
    frames:
      privileged: true
      container_name: xbee
      build: .
      volumes:
        - /boot/firmware/:/app/config_host
      environment:
        - RELEVATOR=big1
networks:
  default:
    external:
      name: ac

